/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete;

import javax.swing.JOptionPane;

/**
 *
 * @author leticia_b_souza
 */
public class TelaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Campocodprod = new javax.swing.JTextField();
        Campocodfilial = new javax.swing.JTextField();
        ExcluirEstoque = new javax.swing.JButton();
        cadastrarEstoque = new javax.swing.JButton();
        PesquisarEstoque = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("ESTOQUE:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Código produto:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Código da filial:");

        Campocodprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocodprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocodprodActionPerformed(evt);
            }
        });

        Campocodfilial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocodfilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocodfilialActionPerformed(evt);
            }
        });

        ExcluirEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExcluirEstoque.setText("EXCLUIR");
        ExcluirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirEstoqueActionPerformed(evt);
            }
        });

        cadastrarEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cadastrarEstoque.setText("CADASTRAR");
        cadastrarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEstoqueActionPerformed(evt);
            }
        });

        PesquisarEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PesquisarEstoque.setText("PESQUISAR");
        PesquisarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campocodprod))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(10, 10, 10)
                            .addComponent(Campocodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cadastrarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PesquisarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ExcluirEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Campocodprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campocodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampocodprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocodprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocodprodActionPerformed

    private void CampocodfilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocodfilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocodfilialActionPerformed

    private void cadastrarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEstoqueActionPerformed
        if (Campocodfilial.getText().equals("") || Campocodprod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
        } else {
            try{
        Estoque e = new Estoque(Integer.parseInt(Campocodprod.getText()), Campocodfilial.getText());
        AcessoBD_lanchonete.salvar_estoque(e);
        Campocodprod.setText("");
        Campocodfilial.setText("");
            JOptionPane.showMessageDialog(this, "Estoque cadastrado!");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Problamas com a filial!");
            }
        }
    }//GEN-LAST:event_cadastrarEstoqueActionPerformed

    private void PesquisarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarEstoqueActionPerformed
        if (Campocodprod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
        } else if(AcessoBD_lanchonete.pesquisa_estoque("estoque", Integer.parseInt(Campocodprod.getText()), Campocodfilial.getText()) != true){
            JOptionPane.showMessageDialog(this, "Estoque não cadastrado");
        }
        else if(AcessoBD_lanchonete.pesquisa_estoque("estoque", Integer.parseInt(Campocodprod.getText()), Campocodfilial.getText()) == true){
            AcessoBD_lanchonete.pesquisa_estoque("produto", Integer.parseInt(Campocodprod.getText()), Campocodfilial.getText());
        }
    }//GEN-LAST:event_PesquisarEstoqueActionPerformed

    private void ExcluirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirEstoqueActionPerformed
        if (Campocodprod.getText().equals("") || Campocodfilial.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos de código corretamente");
        }
        else {
            try{
            AcessoBD_lanchonete.deleta_estoque(Integer.parseInt(Campocodprod.getText()), Campocodfilial.getText());
            JOptionPane.showMessageDialog(this, "Estoque deletado");
            }
             catch(Exception e){
                JOptionPane.showMessageDialog(this, "Estoque não deletado");
                }
        }
    }//GEN-LAST:event_ExcluirEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campocodfilial;
    private javax.swing.JTextField Campocodprod;
    private javax.swing.JButton ExcluirEstoque;
    private javax.swing.JButton PesquisarEstoque;
    private javax.swing.JButton cadastrarEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
