/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete;

import javax.swing.JOptionPane;

/**
 *
 * @author leticia_b_souza
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Campocargofunc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Camponomefunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Campofilialfunc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Campopisfunc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Campocargafunc = new javax.swing.JTextField();
        Camposalariofunc = new javax.swing.JTextField();
        ExcluirFunc = new javax.swing.JButton();
        CadastrarFunc = new javax.swing.JButton();
        PesquisarFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("FUNCIONÁRIO:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Salário:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        Campocargofunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocargofunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocargofuncActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Filial:");

        Camponomefunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camponomefunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamponomefuncActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("PIS:");

        Campofilialfunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campofilialfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampofilialfuncActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Cargo:");

        Campopisfunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campopisfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampopisfuncActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Carga horária:");

        Campocargafunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocargafunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocargafuncActionPerformed(evt);
            }
        });

        Camposalariofunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camposalariofunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamposalariofuncActionPerformed(evt);
            }
        });

        ExcluirFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExcluirFunc.setText("EXCLUIR");
        ExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirFuncActionPerformed(evt);
            }
        });

        CadastrarFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CadastrarFunc.setText("CADASTRAR");
        CadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncActionPerformed(evt);
            }
        });

        PesquisarFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PesquisarFunc.setText("PESQUISAR");
        PesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastrarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addComponent(Camponomefunc))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Campofilialfunc)
                                .addComponent(Campocargofunc, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Camposalariofunc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Campocargafunc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Campopisfunc, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Camponomefunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campofilialfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Campopisfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campocargofunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(Campocargafunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camposalariofunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampocargofuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocargofuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocargofuncActionPerformed

    private void CamponomefuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamponomefuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamponomefuncActionPerformed

    private void CampofilialfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampofilialfuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampofilialfuncActionPerformed

    private void CampopisfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampopisfuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampopisfuncActionPerformed

    private void CampocargafuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocargafuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocargafuncActionPerformed

    private void CamposalariofuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamposalariofuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamposalariofuncActionPerformed

    private void CadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncActionPerformed
        if (Camponomefunc.getText().equals("") || Campopisfunc.getText().equals("") || Camposalariofunc.getText().equals("") || Campocargafunc.getText().equals("") || Campocargofunc.getText().equals("") || Campofilialfunc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
        } else if(AcessoBD_lanchonete.verifica_funcionario(Campofilialfunc.getText()) != true){
            JOptionPane.showMessageDialog(this, "Filial não cadastrada!");
        } else {
        Funcionario_lanchonete fl = new Funcionario_lanchonete(Campopisfunc.getText(), Camponomefunc.getText(), Double.parseDouble(Camposalariofunc.getText()), Campocargofunc.getText(), Integer.parseInt(Campocargafunc.getText()), Campofilialfunc.getText());
          try{
        AcessoBD_lanchonete.salvar_funcionarios(fl);
        Camponomefunc.setText("");
        Campofilialfunc.setText("");
        Campopisfunc.setText("");
        Campocargofunc.setText("");
        Camposalariofunc.setText("");
        Campocargafunc.setText("");
            JOptionPane.showMessageDialog(this, "Funcionario cadastrado!");
        }
          catch(Exception e){
            JOptionPane.showMessageDialog(this, "Funcionario não cadastrado!");
        } 
        }
    }//GEN-LAST:event_CadastrarFuncActionPerformed

    private void PesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarFuncActionPerformed
        if (Campopisfunc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo pis");
        }
            else if(AcessoBD_lanchonete.pesquisa_funcionario("funcionarios_lanchonete", Campopisfunc.getText()) != true){
            JOptionPane.showMessageDialog(this, "Funcionário não cadastrado");
        }
        else if(AcessoBD_lanchonete.pesquisa_funcionario("funcionarios_lanchonete", Campopisfunc.getText()) == true){
            AcessoBD_lanchonete.pesquisa_funcionario("funcionarios_lanchonete", Campopisfunc.getText());
        
        }
    }//GEN-LAST:event_PesquisarFuncActionPerformed

    private void ExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirFuncActionPerformed
        if (Campopisfunc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo pis corretamente");
        }
        else {
            try{
                if(AcessoBD_lanchonete.deleta_funcionarios(Campopisfunc.getText()) == true){
                    AcessoBD_lanchonete.deleta_funcionarios(Campopisfunc.getText());
                    JOptionPane.showMessageDialog(this, "Funcionário deletado");
                }
                if(AcessoBD_lanchonete.deleta_funcionarios(Campopisfunc.getText()) != true){
                    AcessoBD_lanchonete.deleta_funcionarios(Campopisfunc.getText());
                    JOptionPane.showMessageDialog(this, "Funcionário utilizado em outra tabela");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Funcionário não deletado");
            }
        }
    }//GEN-LAST:event_ExcluirFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarFunc;
    private javax.swing.JTextField Campocargafunc;
    private javax.swing.JTextField Campocargofunc;
    private javax.swing.JTextField Campofilialfunc;
    private javax.swing.JTextField Camponomefunc;
    private javax.swing.JTextField Campopisfunc;
    private javax.swing.JTextField Camposalariofunc;
    private javax.swing.JButton ExcluirFunc;
    private javax.swing.JButton PesquisarFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
