/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete;

import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author leticia_b_souza
 */
public class TelaFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public TelaFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarFornecedor1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Campoprodfornec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Camponomefornec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Campoemailfornec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Campocnpjfornec = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Campoestadofornec = new javax.swing.JTextField();
        ExcluirFornecedor = new javax.swing.JButton();
        CadastrarFornecedor = new javax.swing.JButton();
        PesquisarFornecedor = new javax.swing.JButton();

        CadastrarFornecedor1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CadastrarFornecedor1.setText("CADASTRAR");
        CadastrarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFornecedor1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("FORNECEDOR:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        Campoprodfornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campoprodfornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoprodfornecActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("E-mail:");

        Camponomefornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Camponomefornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamponomefornecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("CNPJ:");

        Campoemailfornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campoemailfornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoemailfornecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Produto:");

        Campocnpjfornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocnpjfornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocnpjfornecActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");

        Campoestadofornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campoestadofornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoestadofornecActionPerformed(evt);
            }
        });

        ExcluirFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExcluirFornecedor.setText("EXCLUIR");
        ExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirFornecedorActionPerformed(evt);
            }
        });

        CadastrarFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CadastrarFornecedor.setText("CADASTRAR");
        CadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFornecedorActionPerformed(evt);
            }
        });

        PesquisarFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PesquisarFornecedor.setText("PESQUISAR");
        PesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Camponomefornec, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campoemailfornec, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Campocnpjfornec, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(Campoestadofornec)
                            .addComponent(Campoprodfornec))))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Camponomefornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campoemailfornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Campocnpjfornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campoprodfornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Campoestadofornec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoprodfornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoprodfornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoprodfornecActionPerformed

    private void CamponomefornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamponomefornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamponomefornecActionPerformed

    private void CampoemailfornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoemailfornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoemailfornecActionPerformed

    private void CampocnpjfornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocnpjfornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocnpjfornecActionPerformed

    private void CampoestadofornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoestadofornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoestadofornecActionPerformed

    private void CadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFornecedorActionPerformed
        if (Camponomefornec.getText().equals("") || Campoemailfornec.getText().equals("") || Campocnpjfornec.getText().equals("") || Campoprodfornec.getText().equals("") || Campoestadofornec.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
        } else {
            Fornecedor f = new Fornecedor(Camponomefornec.getText(), Campoemailfornec.getText(), Campocnpjfornec.getText(), Campoprodfornec.getText(), Campoestadofornec.getText());
            try{
        AcessoBD_lanchonete.salvar_fornecedor(f);
        Camponomefornec.setText("");
        Campoemailfornec.setText("");
        Campocnpjfornec.setText("");
        Campoprodfornec.setText("");
        Campoestadofornec.setText("");
        JOptionPane.showMessageDialog(this, "Fornecedor cadastrado!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Fornecedor não cadastrado!");
            }
        }
    }//GEN-LAST:event_CadastrarFornecedorActionPerformed

    private void PesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarFornecedorActionPerformed
        if (Campocnpjfornec.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo cnpj");
        } else if(AcessoBD_lanchonete.pesquisa_compra("compra", Campocnpjfornec.getText()) != true){
            JOptionPane.showMessageDialog(this, "Fornecedor não cadastrado");
        }
        else if(AcessoBD_lanchonete.pesquisa_fornecedor("fornececedor", Campocnpjfornec.getText()) == true){
            AcessoBD_lanchonete.pesquisa_fornecedor("fornececedor", Campocnpjfornec.getText());
        }
    }//GEN-LAST:event_PesquisarFornecedorActionPerformed

    private void ExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirFornecedorActionPerformed
        if (Campocnpjfornec.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo cnpj corretamente");
        }
        else {
            try{
                if (AcessoBD_lanchonete.deleta_fornecedor(Campocnpjfornec.getText()) != true){
                    JOptionPane.showMessageDialog(this, "Fornecededor utilizado em outra tabela");                
                }
                else if (AcessoBD_lanchonete.deleta_fornecedor(Campocnpjfornec.getText()) == true){
                    AcessoBD_lanchonete.deleta_fornecedor(Campocnpjfornec.getText());
                    JOptionPane.showMessageDialog(this, "Fornecededor deletado");
                }   
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Fornecedor não deletado");
            }
        }
    }//GEN-LAST:event_ExcluirFornecedorActionPerformed

    private void CadastrarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFornecedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarFornecedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarFornecedor;
    private javax.swing.JButton CadastrarFornecedor1;
    private javax.swing.JTextField Campocnpjfornec;
    private javax.swing.JTextField Campoemailfornec;
    private javax.swing.JTextField Campoestadofornec;
    private javax.swing.JTextField Camponomefornec;
    private javax.swing.JTextField Campoprodfornec;
    private javax.swing.JButton ExcluirFornecedor;
    private javax.swing.JButton PesquisarFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
