/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete;

import java.awt.Color;

/**
 *
 * @author leticia_b_souza
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AcessarCompra = new javax.swing.JButton();
        AcessarFilial = new javax.swing.JButton();
        AcessarFornec = new javax.swing.JButton();
        AcessarEstoque = new javax.swing.JButton();
        AcessarProd = new javax.swing.JButton();
        AcessarFunc = new javax.swing.JButton();
        VisualizarFornec = new javax.swing.JButton();
        VisualizarEstoque = new javax.swing.JButton();
        VisualizarProd = new javax.swing.JButton();
        VisulizarFunc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        VisulizarCompra = new javax.swing.JButton();
        VisualizarFilial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acessar o banco:");

        AcessarCompra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarCompra.setText("COMPRA");
        AcessarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarCompraActionPerformed(evt);
            }
        });

        AcessarFilial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarFilial.setText("FILIAL");
        AcessarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarFilialActionPerformed(evt);
            }
        });

        AcessarFornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarFornec.setText("FORNECEDOR");
        AcessarFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarFornecActionPerformed(evt);
            }
        });

        AcessarEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarEstoque.setText("ESTOQUE");
        AcessarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarEstoqueActionPerformed(evt);
            }
        });

        AcessarProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarProd.setText("PRODUTO");
        AcessarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarProdActionPerformed(evt);
            }
        });

        AcessarFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcessarFunc.setText("FUNCIONÁRIO");
        AcessarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarFuncActionPerformed(evt);
            }
        });

        VisualizarFornec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisualizarFornec.setText("FORNECEDOR");
        VisualizarFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarFornecActionPerformed(evt);
            }
        });

        VisualizarEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisualizarEstoque.setText("ESTOQUE");
        VisualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarEstoqueActionPerformed(evt);
            }
        });

        VisualizarProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisualizarProd.setText("PRODUTO");
        VisualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarProdActionPerformed(evt);
            }
        });

        VisulizarFunc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisulizarFunc.setText("FUNCIONÁRIO");
        VisulizarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisulizarFuncActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visualizar o banco:");

        VisulizarCompra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisulizarCompra.setText("COMPRA");
        VisulizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisulizarCompraActionPerformed(evt);
            }
        });

        VisualizarFilial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VisualizarFilial.setText("FILIAL");
        VisualizarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarFilialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AcessarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcessarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcessarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcessarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcessarFornec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcessarEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(VisulizarFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarEstoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarFornec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarFilial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisulizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(VisualizarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(VisualizarFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(VisualizarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(VisualizarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(VisulizarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(VisulizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(AcessarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(AcessarFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(AcessarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(AcessarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(AcessarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(AcessarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcessarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarCompraActionPerformed
        TelaCompra compra = new TelaCompra();
        compra.setVisible(true);
    }//GEN-LAST:event_AcessarCompraActionPerformed

    private void AcessarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarFilialActionPerformed
        TelaFilial filial = new TelaFilial();
        filial.setVisible(true);
    }//GEN-LAST:event_AcessarFilialActionPerformed

    private void AcessarFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarFornecActionPerformed
        TelaFornecedor fornecedor = new TelaFornecedor();
        fornecedor.setVisible(true);
    }//GEN-LAST:event_AcessarFornecActionPerformed

    private void AcessarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarEstoqueActionPerformed
        TelaEstoque estoque = new TelaEstoque();
        estoque.setVisible(true);
    }//GEN-LAST:event_AcessarEstoqueActionPerformed

    private void AcessarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarProdActionPerformed
        TelaProduto produto = new TelaProduto();
        produto.setVisible(true);
    }//GEN-LAST:event_AcessarProdActionPerformed

    private void AcessarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarFuncActionPerformed
        TelaFuncionario funcionario = new TelaFuncionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_AcessarFuncActionPerformed

    private void VisualizarFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarFornecActionPerformed
        AcessoBD_lanchonete.visualiza_tabela("fornecedor", "cnpj", "nome", "email", "estado", "produto");
    }//GEN-LAST:event_VisualizarFornecActionPerformed

    private void VisualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarEstoqueActionPerformed
        AcessoBD_lanchonete.visualiza_estoque("cidade", "estado", "nome", "marca", "descricao", "qtd", "validade");
    }//GEN-LAST:event_VisualizarEstoqueActionPerformed

    private void VisualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarProdActionPerformed
        AcessoBD_lanchonete.visualiza_tabela("produto", "codigo_produto", "validade", "qtd", "data_compra", "cod_fornecedor", "marca", "preco", "descricao");
    }//GEN-LAST:event_VisualizarProdActionPerformed

    private void VisulizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisulizarFuncActionPerformed
        AcessoBD_lanchonete.visualiza_tabela("funcionarios_lanchonete", "pis", "nome", "salario", "cargo", "carga_horaria", "cod_filial");
    }//GEN-LAST:event_VisulizarFuncActionPerformed

    private void VisulizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisulizarCompraActionPerformed
        AcessoBD_lanchonete.visualiza_tabela("compra", "cpf_cliente", "data_compra", "total", "cod_func");
    }//GEN-LAST:event_VisulizarCompraActionPerformed

    private void VisualizarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarFilialActionPerformed
        AcessoBD_lanchonete.visualiza_tabela("filial", "cod", "nome", "cidade", "estado");
    }//GEN-LAST:event_VisualizarFilialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcessarCompra;
    private javax.swing.JButton AcessarEstoque;
    private javax.swing.JButton AcessarFilial;
    private javax.swing.JButton AcessarFornec;
    private javax.swing.JButton AcessarFunc;
    private javax.swing.JButton AcessarProd;
    private javax.swing.JButton VisualizarEstoque;
    private javax.swing.JButton VisualizarFilial;
    private javax.swing.JButton VisualizarFornec;
    private javax.swing.JButton VisualizarProd;
    private javax.swing.JButton VisulizarCompra;
    private javax.swing.JButton VisulizarFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
