/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete;

import javax.swing.JOptionPane;

/**
 *
 * @author leticia_b_souza
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Campomarcaprod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Campocodprod = new javax.swing.JTextField();
        Campoprecoprod = new javax.swing.JTextField();
        Campofornecprod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Campoqtdprod = new javax.swing.JTextField();
        Campodescprod = new javax.swing.JTextField();
        Campovalprod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Campodataprod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CadastrarProd = new javax.swing.JButton();
        PesquisarProd = new javax.swing.JButton();
        ExcluirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Marca:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("PRODUTO:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Fornecedor:");

        Campomarcaprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campomarcaprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampomarcaprodActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Código:");

        Campocodprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campocodprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampocodprodActionPerformed(evt);
            }
        });

        Campoprecoprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campoprecoprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoprecoprodActionPerformed(evt);
            }
        });

        Campofornecprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campofornecprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampofornecprodActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Preço:");

        Campoqtdprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campoqtdprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoqtdprodActionPerformed(evt);
            }
        });

        Campodescprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campodescprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampodescprodActionPerformed(evt);
            }
        });

        Campovalprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campovalprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampovalprodActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Validade:");

        Campodataprod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Campodataprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampodataprodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Data compra:");

        CadastrarProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CadastrarProd.setText("CADASTRAR");
        CadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdActionPerformed(evt);
            }
        });

        PesquisarProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PesquisarProd.setText("PESQUISAR");
        PesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarProdActionPerformed(evt);
            }
        });

        ExcluirProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ExcluirProd.setText("EXCLUIR");
        ExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Campofornecprod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Campocodprod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(21, 21, 21)
                                    .addComponent(Campodescprod))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(10, 10, 10)
                                    .addComponent(Campoqtdprod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addGap(10, 10, 10)
                                    .addComponent(Campoprecoprod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Campomarcaprod, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Campodataprod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Campovalprod, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(Campocodprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campofornecprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campodescprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Campoprecoprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Campoqtdprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campomarcaprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Campovalprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Campodataprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampomarcaprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampomarcaprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampomarcaprodActionPerformed

    private void CampocodprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampocodprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampocodprodActionPerformed

    private void CampoprecoprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoprecoprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoprecoprodActionPerformed

    private void CampofornecprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampofornecprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampofornecprodActionPerformed

    private void CampoqtdprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoqtdprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoqtdprodActionPerformed

    private void CampodescprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampodescprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampodescprodActionPerformed

    private void CampovalprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampovalprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampovalprodActionPerformed

    private void CampodataprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampodataprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampodataprodActionPerformed

    private void CadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdActionPerformed
        if (Campocodprod.getText().equals("") || Campodataprod.getText().equals("") || Campodescprod.getText().equals("") || Campofornecprod.getText().equals("") || Campomarcaprod.getText().equals("") || Campoprecoprod.getText().equals("") || Campoqtdprod.getText().equals("") || Campovalprod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente");
        }
        else if(AcessoBD_lanchonete.verifica_produto(Campofornecprod.getText()) != true){
            JOptionPane.showMessageDialog(this, "Cadastre um forncecedor!");
        }
        else{
            try{
            Produto p = new Produto(Integer.parseInt(Campocodprod.getText()), Campovalprod.getText(), Integer.parseInt(Campoqtdprod.getText()), Campodataprod.getText(), Campofornecprod.getText(), Campomarcaprod.getText(), Double.parseDouble(Campoprecoprod.getText()), Campodescprod.getText());
            AcessoBD_lanchonete.salvar_produto(p);
            Campocodprod.setText("");
            Campodataprod.setText("");
            Campodescprod.setText("");
            Campofornecprod.setText("");
            Campomarcaprod.setText("");
            Campoprecoprod.setText("");
            Campoqtdprod.setText("");
            Campovalprod.setText("");
            JOptionPane.showMessageDialog(this, "Produto cadastrado!");
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Produto não cadastrado, dados inválidos!");
            }
        }
    }//GEN-LAST:event_CadastrarProdActionPerformed

    private void PesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarProdActionPerformed
        if (Campocodprod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo código");
        } else if(AcessoBD_lanchonete.pesquisa_produto("produto", Integer.parseInt(Campocodprod.getText())) != true){
            JOptionPane.showMessageDialog(this, "Produto não cadastrado");
        }
        else if(AcessoBD_lanchonete.pesquisa_produto("produto", Integer.parseInt(Campocodprod.getText())) == true){
            AcessoBD_lanchonete.pesquisa_produto("produto", Integer.parseInt(Campocodprod.getText()));
        }
    }//GEN-LAST:event_PesquisarProdActionPerformed

    private void ExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirProdActionPerformed
        if (Campocodprod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo código corretamente");
        }
        else {
             try{
                 if (AcessoBD_lanchonete.deleta_produto(Integer.parseInt(Campocodprod.getText())) == true){
                     AcessoBD_lanchonete.deleta_produto(Integer.parseInt(Campocodprod.getText()));
                    JOptionPane.showMessageDialog(this, "Produto deletado");
                 }
                 else if(AcessoBD_lanchonete.deleta_produto(Integer.parseInt(Campocodprod.getText())) != true){
                     JOptionPane.showMessageDialog(this, "Produto utilizado em outra tabela");
                 }
        }
             catch(Exception e){
                JOptionPane.showMessageDialog(this, "Produto não deletado");
             }
        }
    }//GEN-LAST:event_ExcluirProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarProd;
    private javax.swing.JTextField Campocodprod;
    private javax.swing.JTextField Campodataprod;
    private javax.swing.JTextField Campodescprod;
    private javax.swing.JTextField Campofornecprod;
    private javax.swing.JTextField Campomarcaprod;
    private javax.swing.JTextField Campoprecoprod;
    private javax.swing.JTextField Campoqtdprod;
    private javax.swing.JTextField Campovalprod;
    private javax.swing.JButton ExcluirProd;
    private javax.swing.JButton PesquisarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
